name: dol
description: App do Site DiamanteOnline.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
   sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  onesignal_flutter: ^5.3.4
  webview_flutter: ^4.13.1
  device_info_plus: ^12.3.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  #color: "#0095FF"
  background_image: assets/splash.png
  fullscreen: true
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/icone.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/icone-adaptive.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

